"""Event logs: the data every GLM instrument reads.

Times are in units where the environment's nominal mean rate is 1 (the truth
sampler calibrates to that operating point, SPEC §3); ψ grids assume it.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass

import numpy as np
import numpy.typing as npt

from sciagent.core.errors import SciAgentError

type Floats = npt.NDArray[np.float64]


class EventLogError(SciAgentError):
    """An event log is malformed."""


@dataclass(frozen=True, eq=False)
class EventLog:
    """Strictly increasing event times on ``[0, horizon]`` with per-event marks.

    ``marks`` maps a channel name to one float per event. Construct through
    :meth:`create`, which validates and freezes the arrays.
    """

    times: Floats
    marks: Mapping[str, Floats]
    horizon: float

    @staticmethod
    def create(
        times: npt.ArrayLike, marks: Mapping[str, npt.ArrayLike], horizon: float
    ) -> EventLog:
        t = np.array(times, dtype=np.float64)
        if t.ndim != 1:
            raise EventLogError("times must be one-dimensional")
        if not np.isfinite(horizon) or horizon <= 0:
            raise EventLogError(f"horizon must be positive and finite: {horizon}")
        if t.size and (t[0] < 0 or t[-1] > horizon):
            raise EventLogError("event times must lie in [0, horizon]")
        if t.size > 1 and not np.all(np.diff(t) > 0):
            raise EventLogError("event times must be strictly increasing")
        frozen: dict[str, Floats] = {}
        for name in sorted(marks):
            m = np.array(marks[name], dtype=np.float64)
            if m.shape != t.shape:
                raise EventLogError(f"mark {name!r} has shape {m.shape}, not {t.shape}")
            if not np.all(np.isfinite(m)):
                raise EventLogError(f"mark {name!r} has non-finite values")
            m.setflags(write=False)
            frozen[name] = m
        t.setflags(write=False)
        return EventLog(times=t, marks=frozen, horizon=float(horizon))

    @property
    def n(self) -> int:
        return int(self.times.size)


@dataclass(frozen=True, eq=False)
class Dataset:
    """An event log plus what the likelihood needs to know about how it arose.

    ``log`` holds every observed event, forced ones included: all of them are
    history for the features. ``endogenous[i]`` is True when event i was
    generated by the intensity λ, so it contributes ``log λ(tᵢ)``. Forced
    events are exogenous: they excite, but they are not evidence about λ.
    ``excluded`` holds sorted, disjoint intervals of ``[0, horizon]`` on which
    the model's λ did not govern what was observed: clamped-rate windows and
    censoring windows. They are removed from the compensator, and any
    endogenous event inside one is not counted. A likelihood over several
    datasets is the sum of their log-likelihoods, each with its own history
    starting at time 0.

    Censoring makes the likelihood approximate. A censored event happened and
    may have excited later events, but it is missing from ``log``.
    """

    log: EventLog
    endogenous: npt.NDArray[np.bool_]
    excluded: tuple[tuple[float, float], ...]
    label: str

    @staticmethod
    def create(
        log: EventLog,
        endogenous: npt.ArrayLike,
        excluded: tuple[tuple[float, float], ...],
        label: str,
    ) -> Dataset:
        mask = np.array(endogenous, dtype=np.bool_)
        if mask.shape != log.times.shape:
            raise EventLogError(f"endogenous mask has shape {mask.shape}")
        previous_end = 0.0
        for start, end in excluded:
            if not (previous_end <= start < end <= log.horizon):
                raise EventLogError(
                    f"excluded intervals must be sorted, disjoint, inside "
                    f"[0, horizon]: {excluded}"
                )
            previous_end = end
        mask.setflags(write=False)
        return Dataset(log=log, endogenous=mask, excluded=tuple(excluded), label=label)

    @staticmethod
    def observational(log: EventLog, label: str = "observational") -> Dataset:
        return Dataset.create(log, np.ones(log.n, dtype=np.bool_), (), label)
